services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app:/app/src
      - ASYNC_DATABASE_URI=sqlite+aiosqlite:///test.db
      - TESTING=True