services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URI=sqlite:////app/src/instance/recipes.db
      - ASYNC_DATABASE_URI=sqlite+aiosqlite:////app/src/instance/recipes.db
      - DEBUG=1
    volumes:
      - .:/app
      - db-data:/app/src/instance:rw
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: