services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app
      - FLASK_DEBUG=1
      - PYTHONPATH=/app/src:/app
    volumes:
      - ./src/instance:/app/src/instance