"""
This type stub file was generated by pyright.
"""

import sys # type: ignore
from collections.abc import OrderedDict # type: ignore
from werkzeug.http import HTTP_STATUS_CODES # type: ignore

PY3 = ...
def http_status_message(code): # -> str:# type: ignore
    """Maps an HTTP status code to the textual status"""
    ...

def unpack(value): # type: ignore
    """Return a three tuple of data, code, and headers"""
    ...

