"""
This type stub file was generated by pyright.
"""

import logging
import os
import sys
from .cs50 import get_char, get_float, get_int, get_long, get_string
from . import flask
from .sql import SQL

